# Generated by Django 6.0.3 on 2026-04-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=200)),
                ('stars', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('created_at', models.CharField(max_length=1000)),
            ],
        ),
    ]
