# Generated by Django 5.2.13 on 2026-04-24 01:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=1000)),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('url', models.URLField(max_length=1000)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'GitHub API')], default='csv', max_length=10)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repos', to='core.language')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='core.user')),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'ordering': ['-stars'],
                'unique_together': {('repo_name', 'owner')},
            },
        ),
    ]
